services:
  app1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DB_HOST={DB}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB}
    depends_on:
      - db

  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_PASS}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "13330:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
