version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${PROD_DB_HOST}
      - DB_PORT=${PROD_DB_PORT}
      - DB_USER=${PROD_DB_USER}
      - DB_PASSWORD=${PROD_DB_PASSWORD}
      - DB_NAME=${PROD_DB_DATABASE}
    depends_on:
      - db

  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${PROD_DB_DATABASE}
      MYSQL_USER: ${PROD_DB_USER}
      MYSQL_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - "13331:13331"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
